<?php
/**
 * File:        class-flat-api-security.php
 * Description: Shared response, export, and resource-limit safeguards.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class Formidable_Flat_API_Security {

    /**
     * Return validated export limits for a particular execution context.
     *
     * Browser-submitted rows are intentionally bounded more tightly than rows
     * generated by a trusted saved query on the server. Sites with legitimate
     * larger workloads can adjust these values without editing the plugin.
     */
    public static function export_limits( $context = 'server' ) {
        $filtered = ( 'filtered_xlsx' === $context );
        $defaults = [
            'max_request_bytes' => $filtered ? 5 * MB_IN_BYTES : 0,
            'max_rows'          => $filtered ? 10000 : 100000,
            'max_columns'       => 250,
            'max_cell_chars'    => 32767,
        ];

        $limits = apply_filters( 'formidable_flat_api_export_limits', $defaults, $context );
        if ( ! is_array( $limits ) ) $limits = $defaults;

        foreach ( $defaults as $key => $default ) {
            $value = isset( $limits[ $key ] ) ? (int) $limits[ $key ] : $default;
            $limits[ $key ] = ( 'max_request_bytes' === $key )
                ? max( 0, $value )
                : max( 1, $value );
        }

        return $limits;
    }

    /**
     * Maximum number of rows which may be returned from a core REST endpoint.
     */
    public static function rest_max_rows() {
        $maximum = (int) apply_filters( 'formidable_flat_api_rest_max_rows', 100000 );
        return max( 1, $maximum );
    }

    /**
     * Reject a raw browser export payload before JSON decoding when it is too
     * large. This bounds JSON parser and XLSX-generation memory pressure.
     */
    public static function validate_request_size( $raw, $context = 'filtered_xlsx' ) {
        $limits = self::export_limits( $context );
        if (
            $limits['max_request_bytes'] > 0
            && strlen( (string) $raw ) > $limits['max_request_bytes']
        ) {
            return new WP_Error(
                'ffapi_export_request_too_large',
                'The export request is too large.',
                [ 'status' => 413 ]
            );
        }
        return true;
    }

    /**
     * Validate and normalize tabular rows before writing an export.
     *
     * Returns [ 'headers' => string[], 'rows' => array[] ] or WP_Error.
     */
    public static function prepare_export_rows(
        array $rows,
        array $allowed_columns = [],
        $context = 'server'
    ) {
        $limits = self::export_limits( $context );
        if ( count( $rows ) > $limits['max_rows'] ) {
            return new WP_Error(
                'ffapi_export_too_many_rows',
                sprintf( 'The export exceeds the %d-row limit.', $limits['max_rows'] ),
                [ 'status' => 413 ]
            );
        }

        $allowed_lookup = [];
        foreach ( $allowed_columns as $column ) {
            $column = (string) $column;
            if ( '' !== $column ) $allowed_lookup[ $column ] = true;
        }

        $seen_headers = [];
        foreach ( $rows as $row ) {
            if ( ! is_array( $row ) ) {
                return new WP_Error(
                    'ffapi_export_invalid_row',
                    'The export contains a non-tabular row.',
                    [ 'status' => 400 ]
                );
            }

            foreach ( array_keys( $row ) as $header ) {
                $header = (string) $header;
                if ( '' === $header ) {
                    return new WP_Error(
                        'ffapi_export_invalid_column',
                        'The export contains an empty column name.',
                        [ 'status' => 400 ]
                    );
                }
                if ( $allowed_lookup && ! isset( $allowed_lookup[ $header ] ) ) {
                    return new WP_Error(
                        'ffapi_export_unknown_column',
                        'The export contains a column which is not part of the saved query.',
                        [ 'status' => 400 ]
                    );
                }
                $seen_headers[ $header ] = true;
            }
        }

        if ( count( $seen_headers ) > $limits['max_columns'] ) {
            return new WP_Error(
                'ffapi_export_too_many_columns',
                sprintf( 'The export exceeds the %d-column limit.', $limits['max_columns'] ),
                [ 'status' => 413 ]
            );
        }

        $headers = [];
        if ( $allowed_lookup ) {
            foreach ( $allowed_columns as $header ) {
                $header = (string) $header;
                if ( isset( $seen_headers[ $header ] ) ) $headers[] = $header;
            }
        } else {
            $headers = array_keys( $seen_headers );
        }

        $normalized = [];
        foreach ( $rows as $row ) {
            $normalized_row = [];
            foreach ( $headers as $header ) {
                $value = $row[ $header ] ?? '';
                if ( is_array( $value ) || is_object( $value ) ) {
                    $value = wp_json_encode( $value );
                    if ( false === $value ) $value = '';
                } elseif ( is_bool( $value ) ) {
                    $value = $value ? '1' : '0';
                } elseif ( null === $value ) {
                    $value = '';
                }

                if (
                    is_string( $value )
                    && mb_strlen( $value ) > $limits['max_cell_chars']
                ) {
                    return new WP_Error(
                        'ffapi_export_cell_too_large',
                        sprintf(
                            'A value in column "%s" exceeds the %d-character limit.',
                            $header,
                            $limits['max_cell_chars']
                        ),
                        [ 'status' => 413 ]
                    );
                }
                $normalized_row[ $header ] = $value;
            }
            $normalized[] = $normalized_row;
        }

        return [
            'headers' => $headers,
            'rows'    => $normalized,
        ];
    }

    /**
     * Neutralize values which spreadsheet programs may execute as CSV formulae.
     *
     * Numeric values, including negative numbers, remain numeric. The XLSX writer
     * already serializes non-numeric values as inline strings, so this helper is
     * needed only by CSV output.
     */
    public static function csv_safe_value( $value ) {
        if ( ! is_string( $value ) || is_numeric( $value ) ) return $value;
        if ( preg_match( '/^[\x00-\x20]*[=+\-@]/u', $value ) ) return "'" . $value;
        return $value;
    }

    /**
     * Return a bounded result or a REST error instead of emitting an oversized
     * response body.
     */
    public static function enforce_rest_row_limit( array $rows ) {
        $maximum = self::rest_max_rows();
        if ( count( $rows ) > $maximum ) {
            return new WP_Error(
                'ffapi_rest_result_too_large',
                sprintf( 'The query result exceeds the %d-row REST limit.', $maximum ),
                [ 'status' => 413 ]
            );
        }
        return $rows;
    }
}
